#!/bin/bash

cat > .git/hooks/post-commit <<'END'
#!/bin/bash

set -o pipefail

needsUpdate () {
    echo "**********************************************" >&2
    echo "$*; to fix, run:" >&2
    echo "  ./manage/update-package-catalog" >&2
    echo "**********************************************" >&2
	exit 1
}

if [[ ! -e manage/package-catalog ]]; then
    needsUpdate 'package-catalog does not exist'
else
    find packages -maxdepth 1 -mindepth 1 -type d -printf '%P\n' | \
        diff --brief manage/package-catalog - >/dev/null
    diffResult=$?
    if [[ $diffResult -eq 1 ]]; then
        needsUpdate 'package-catalog needs updating'
    elif [[ $diffResult -ne 0 ]]; then
        echo "error running find or diff: $diffResult" >&2
        exit $diffResult
    fi
fi
END
